### ISSUE TITLE
Production Build Errors

### ISSUE THREAD

**Issue by sarastrasner** [epilocal/newsliner-gatsby#1]
1. Production build with 'npm run build' failed initially with the following error: 'Something went wrong installing the "sharp" module'.  
'Reason: Incompatible library version: sharp-darwin-x64.node requires version
56.0.0 or later, but libvips-cpp.42.dylib provides version 55.0.0'
Ran the following suggested solution: 'brew update && brew upgrade vips' and 'npm i vips'. The error 'Error: vips not installed' persisted. 
2. Also tried 'npm audit fix --force' then 'npm run build' and got the following error: 'Error: cheerio.load() expects a string'
'npm run dev' runs successfully and renders the site locally

**Comment by gjdickens** [comment]
Just pushed a fix now.  

The RSS feed generation in utils/rss/generate-feed.js was failing as Ghost posts marked with an internal tag return no html from the content API.  In the fix, I filtered these out from the RSS feed.
